### ISSUE TITLE
Event time or device time

### ISSUE THREAD

**Issue by johnjohndoe** [EventFahrplan/EventFahrplan#69] opened 2018-07-02 20:42 UTC
Date and time are shown in different parts of the app such as:

- Time column on the side of the tabular view
- Event details
- Share message
- Calendar export

Users should be able to choose how the date/time is displayed such as:

- Based on the time zone of where the event takes place (event time or local time)
- Based on the time zone settings of their device (device time or home time)

---

:point_up: Side note for the implementation: the long term goal is to replace all app date handling with [ThreeTen-Backport libraries](https://www.threeten.org/threetenbp/). It might be possible to do the migraton as part of this issue. Let's discuss.

**Comment by rugk** [comment] 2019-12-31 21:50
Duplicate of https://github.com/EventFahrplan/EventFahrplan/issues/70 (double post?)

**Comment by johnjohndoe** [comment] 2020-01-01 16:26
Issue #70 only addresses the system setting where users can choose between 12- and 24-hours format. This issue is about providing an in-app setting to let users decide whether date/time information should be displayed in their local time zone or in the time zone of the event.

I agree that the two issues are certainly related but since this issue involves work to be done in the UI of the app I like to keep them separated.

**Closed** 2021-03-03 21:35 UTC
Labels: Date & time, Feature request
