### ISSUE TITLE
Missing talks in default schedule, visible with alternative Fahrplan URL

### ISSUE THREAD

**Issue by jmozmoz** [EventFahrplan/EventFahrplan#700] opened 2024-12-21 17:52 UTC
# Environment
- App version: 1.68.0
- Android version: 14
- Branch: F-Droid (?) Build Time: 2024-11-30T20:46Z, Version Code 106, Version-Hash: d33c36e4-dirty
- Device: Sony Xperia 10 IV

# How to reproduce
1. Just look at the list of talks, e. g. for day 1 of 38c3. Some talks a missing, e. g. these: https://fahrplan.events.ccc.de/congress/2024/fahrplan/talk/7RBKND/, https://fahrplan.events.ccc.de/congress/2024/fahrplan/talk/GUFA37/
2. Also the talks can not be searched for.

# Observed behavior
- Empty space in schedule is shown for missing talks.

# Expected behavior
- Talks are shown.

If this alternative URL Fahrplan is used, the talks are visible: https://fahrplan.events.ccc.de/congress/2024/fahrplan/schedule/export/schedule.xml

The app claimed that the Fahrplan version was up to date with the default URL. 

Fahrplan version with build-in URL: 2024-12-21 18:48

Fahrplan version with alternative URL: 0.9-prod

**Comment by johnjohndoe** [comment] 2024-12-21 20:09
Thank you for the report. This might be caused by IDs being used more than once in the full schedule. Could you check this? This is the URL of the full schedule:  https://api.events.ccc.de/congress/2024/schedule.xml

**Comment by johnjohndoe** [comment] 2024-12-21 20:27
Related: https://github.com/voc/schedule/issues/63

**Comment by jmozmoz** [comment] 2024-12-21 20:56
> This is the URL of the full schedule: https://api.events.ccc.de/congress/2024/schedule.xml

With this URL the talks are also missing

**Comment by johnjohndoe** [comment] 2024-12-21 21:40
`id=137` in `<event guid="8b046ea5-bf0a-58fd-9c2a-4f6ee9e87bd3" id="137">` is used for two sessions. Hence, one is dropped. This must be addressed in the backend. I try to resolve this. Hang on.

**Comment by saerdnaer** [comment] 2024-12-22 14:07
Hier haben zwei verschiedene Pretix Instanzen die selbe Submission Integer ID vergeben. Im Hub gibt es dafür bisher leider keinen Mechanismus pro Quelle einen extra Integer Offset zu definieren.

**Comment by johnjohndoe** [comment] 2024-12-22 14:33
@jmozmoz I will not be able to fix this myself in the app nor in the backend till Congress due to lack of access to a computer. 

If nobody volunteers this won't be fixed early enough. Sorry.

**Comment by schildbach** [comment] 2024-12-25 09:07
I analyzed the duplicates and currently there are currently 14 of them. More could appear as more events and schedules are added to the merged schedule.

```
$ curl -s https://api.events.ccc.de/congress/2024/schedule.xml | xmllint --xpath 'schedule/day/room/event/@id' - | sort | uniq -c -d
      2  id="135"
      2  id="137"
      2  id="158"
      2  id="159"
      2  id="161"
      2  id="167"
      2  id="178"
      2  id="180"
      2  id="191"
      2  id="192"
      2  id="193"
      2  id="198"
      2  id="206"
      2  id="215"
```

**Comment by johnjohndoe** [comment] 2024-12-25 17:57
Backend work: https://git.cccv.de/hub/hub/-/issues/686#note\_31170

**Comment by johnjohndoe** [comment] 2024-12-25 19:10
💡 The `id_unique` constraint can also be validated by the [c3voc schema validator](https://c3voc.de/schedulexml/validate).

**Comment by girst** [comment] 2024-12-26 11:21
until this problem persists, i've made a schedule of only the five curated halls (main track, plus community-stages. a cronjob (should) update this every 10minutes. no guarantees for anything, though :^)

https://services.gir.st/pub/schedule.xml

**Comment by saerdnaer** [comment] 2024-12-26 12:26
@girst You could simply read the documentation at https://c3voc.de/wiki/events:38c3:schedule 
> CCC (die 5 kuratierten Säle): https://api.events.ccc.de/congress/2024/assembly/6840c453-af5c-413c-8127-adcbdcd98e9e/schedule.xml / [schedule.json](https://api.events.ccc.de/congress/2024/assembly/6840c453-af5c-413c-8127-adcbdcd98e9e/schedule.json)

Also https://git.cccv.de/hub/hub/-/merge_requests/1148 is deployed in a few minutes to PROD which fixes https://git.cccv.de/hub/hub/-/issues/686 and https://git.cccv.de/hub/hub/-/issues/675

**Comment by johnjohndoe** [comment] 2024-12-26 12:38
@jmozmoz, @schildbach This has been fixed in the backend now. @saerdnaer and anyone who help, thank you for your time!!

**Closed by johnjohndoe** 2024-12-26 12:38 UTC
Labels: Bug report, Fixed outside the app

**Comment by neobrain** [comment] 2024-12-26 12:41
Thanks to all involved! I was one of the people whose session wasn't visible, so the quick fix (even more so during the holidays) is really appreciated :)
