### ISSUE TITLE
Going back from the event details to the schedule is slow

### ISSUE THREAD

**Issue by lhoff94** [EventFahrplan/EventFahrplan#108] opened 2018-12-27 18:48 UTC
It takes up to 3 seconds to leave the event detail page and go back to the schedule. 

Tested on 3 different devices.

**Comment by micb25** [comment] 2018-12-28 01:42
I can confirm this bug for two more devices.

**Comment by ThomasWaldmann** [comment] 2018-12-28 14:02
I have an idea for a solution that does not require refactoring the main view:

On the detail page, there is a nav button "back" that returns to the main view, causing the performance issue as it has to render all the items all the time (on my Nexus 6, this takes 8s now, which is a real pain).

When freshly installing the app with the intention to look through all the talks (and favorite the interesting ones), it is not needed to render the main view all the time.

The only thing missing is to add 2 additional nav buttons, that selects previous / next session in the same room. No need to return to the main view all the time, performance problems avoided.

Greetings from the Borg. :)

**Comment by AnyTimeTraveler** [comment] 2018-12-29 23:13
It seems to me like 'builing' the calendar-view takes the most time. Is it maybe possible to 'cache' the calendar-activity whenever the details of an event are opened and return to the 'cached' calendar-view instead of rebuiling it?

**Comment by hkahl** [comment] 2018-12-30 13:59
Also an issue when starting the app, resuming the app, or rotating the device. The app (main thread) is blocked for over 10 seconds on my devices.

MainFragment.onCreate(): 4.4s
  -> sql queries take most of the time

FahrplanFragment.onResume(): 7.82s
  -> most of the time in FahrplanFragment.fillRoom()

![profiling](https://user-images.githubusercontent.com/5089630/50547836-9e04cb80-0c42-11e9-9ff4-e1a04a997e6f.png)

**Comment by johnjohndoe** [comment] 2018-12-30 20:15
@hkahl Thank you for the performance analysis. I looked into this before 35c3 myself. From what I analyzed and know about the implementation the source of the performance issue is that the grid view does not recycle any views. The view is **not** based on `RecyclerView` or similar which would easily handle the amount of views. Therefore, the whole schedule "grid" is calculated and **inflated every time**.
Besides this I identified a few minor optimizations but none of them are helping to overcome the overall rendering issue.

To everyone interested in this issue: I am happy to **discuss options** to resolve this issue as soon as possible. Please let us figure out an approach here before someone invests a lot of **time in coding** something which cannot be merged upstream.

**Comment by lhoff94** [comment] 2018-12-30 20:32
Another suggestion. 
Some of you may know the öffi app. It has a really nice view for the result page. Since it was open sourced couple of months ago looking at how they implemented that view and if it would be easier to use their code as a base instead .
I haven't looked into that but maybe it's worth a shot.
Code can be found here:
https://gitlab.com/oeffi/oeffi

**Comment by johnjohndoe** [comment] 2019-02-22 09:09
It might be worth evaluating the [TimetableLayout library](https://github.com/MoyuruAizawa/TimetableLayout) as a replacement for the custom table view which is used in the app.

**Comment by ideadapt** [comment] 2020-03-16 21:46
I have created a quick and dirty PoC using RecyclerView. The result:
![recyclerviewpoc](https://user-images.githubusercontent.com/1071386/76801933-e7552280-67d6-11ea-8653-e5f01e975f73.gif)

It felt like, doing a proper implementation, that has equivalent functionality to what the UI has today, wouldn't be too hard, since most of the existing code (i.e. column snap scroller, row / column calculations) can be reused.

I had a quick look at TimetableLayout which also looks quite elaborated. Maybe its worth a PoC as well. But I feel like it would require more code changes (and introduces a new third dependency). 
[Öffi](https://gitlab.com/oeffi/oeffi), [Giggity](https://github.com/Wilm0r/giggity/) and TimetableLayout all work with RecyclerView in some way. At last, we can for sure learn from their code base, even if we don't integrate it directly.

**Closed** 2020-05-03 19:03 UTC
Labels: Bug report, UX

**Comment by johnjohndoe** [comment] 2020-05-03 19:09
:loudspeaker: Big shoutout to @ideadapt for his efforts to speeding up the app. :racing_car: Thanks a lot.
Everyone here please give him a hand :clap:

**Comment by ByteHamster** [comment] 2020-07-26 19:40
Thanks for working on this issue. I was glad to hear that the slowness is fixed.
Unfortunately, I still experience that problem in version 1.44.0.

Steps to reproduce:
- Open the details view of a talk
- Leave the app using the home button
- Wait until Android kills the app. This can be sped up by using the Background processes limit in developer options
- Go back to EventFahrplan using Android's task switcher screen
- *The details view is opened immediately*
- Press the "up" arrow
- *The app freezes for a few seconds (5 on my phone) before showing the timetable*

**Comment by johnjohndoe** [comment] 2020-07-26 19:48
@ByteHamster Thanks for the report. Can you please specify which Android version and phone model you are using?

**Comment by ByteHamster** [comment] 2020-07-26 20:55
Sorry for that. I use a OnePlus 3T with LineageOS 17.1 (Android 10). It is pretty interesting that I can not reproduce this using an Android 9 or Android 10 emulator using the same apk. This made me curious, so I cloned the project. Now running version 1.44.0-DEBUG (2bae5e49ea0cd7f12132b4f433652514100d9ccc) with the default fahrplan data.

The profiler shows a pretty active main thread during the freeze:

<img width="500" src="https://user-images.githubusercontent.com/5811634/88488940-371bd580-cf91-11ea-90db-93574eafdd3a.png" />

Here is a flame chart showing how much time is spent in each method. Note that the highlighted total in the bottom is actually 11 seconds, using a profiling duration that was not much longer than that.

<img width="400" src="https://user-images.githubusercontent.com/5811634/88489077-57985f80-cf92-11ea-936c-272eb9cc4d62.png" />

The logs I get during freeze are the following:

```
2020-07-26 22:35:50.049 10946-10946/info.metadude.android.congress.schedule.debug D/MetaDatabaseRepository: query(): Meta(eTag=W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 707; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2020-01-18 18:10)
2020-07-26 22:35:50.718 10946-10946/info.metadude.android.congress.schedule.debug D/Fahrplan: onResume
2020-07-26 22:35:50.719 10946-10946/info.metadude.android.congress.schedule.debug D/Fahrplan: sessionId = null
2020-07-26 22:35:50.719 10946-10946/info.metadude.android.congress.schedule.debug D/Fahrplan: MyApp.task_running = NONE
2020-07-26 22:35:50.719 10946-10946/info.metadude.android.congress.schedule.debug D/Fahrplan: meta.getNumDays() = 4
2020-07-26 22:35:50.719 10946-10946/info.metadude.android.congress.schedule.debug D/Fahrplan: viewDay(false)
2020-07-26 22:35:50.721 10946-10946/info.metadude.android.congress.schedule.debug D/AppRepository: Loading sessions for day 1.
2020-07-26 22:35:50.761 10946-10946/info.metadude.android.congress.schedule.debug D/AppRepository: Got 297 rows.
2020-07-26 22:35:50.767 10946-10946/info.metadude.android.congress.schedule.debug D/AlarmsDatabaseRepository: No alarms found.
2020-07-26 22:35:50.770 10946-10946/info.metadude.android.congress.schedule.debug D/AppRepository: 297 uncanceled sessions.
2020-07-26 22:35:50.925 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Beginners Workshop: How to Hack your Web Application collides with Beginners Workshop: How to Hack your Web Application
2020-07-26 22:35:50.942 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Create affinity groups - a game collides with Reprostreik
2020-07-26 22:35:50.954 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Tripod collides with Lambe Lambe: Conglomerate of Experiences: BLODEUWEDD/Dideldum/The Abyss/Anasyrma Temple
2020-07-26 22:35:50.967 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: REBOOT THAI STYLE: Learn how to thai massage your nerdy cramps away collides with CV DAZZLE: Facial Treatment against Facial Recognition
2020-07-26 22:35:50.979 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Factorio collides with Selbstgebaute Musik
2020-07-26 22:35:50.980 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Selbstgebaute Musik collides with T-Shirt Druck
2020-07-26 22:35:50.980 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Calliope collides with Selbstgebaute Musik
2020-07-26 22:35:50.984 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Curtisannes Cake Center collides with Introduction to Tempeh Making
2020-07-26 22:35:50.984 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Detox Seaweed Bibimbab collides with Introduction to Beef Jerky Drying Boxes
2020-07-26 22:35:50.985 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Cidre Making collides with Whisky Tasting
2020-07-26 22:35:50.990 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Performance tentacular mapping collides with Tentacular Mapping:
2020-07-26 22:35:50.994 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Hacking Licence collides with Datenschutz-Sprechstunde mit den Aufsichtsbehörden
2020-07-26 22:35:50.995 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Datenschutz-Sprechstunde mit den Aufsichtsbehörden collides with Hacking Licence
2020-07-26 22:35:50.997 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Learn To Solder collides with Meet and solder the Bill Badge
2020-07-26 22:35:50.997 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Meet and solder the Bill Badge collides with Surface mount electronics assembly for terrified beginners
2020-07-26 22:35:50.998 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: Surface mount electronics assembly for terrified beginners collides with TacTacLights Nano Colour Reflow Soldering
2020-07-26 22:35:50.998 10946-10946/info.metadude.android.congress.schedule.debug D/LayoutCalculator: TacTacLights Nano Colour Reflow Soldering collides with Fomu
2020-07-26 22:35:51.124 10946-10946/info.metadude.android.congress.schedule.debug D/Fahrplan: MyApp.meta = Meta(eTag=W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 707; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2020-01-18 18:10)
2020-07-26 22:35:51.816 10946-10946/info.metadude.android.congress.schedule.debug I/Choreographer: Skipped 115 frames!  The application may be doing too much work on its main thread.
2020-07-26 22:35:54.484 10946-10959/info.metadude.android.congress.schedule.debug I/.schedule.debu: Background concurrent copying GC freed 33598(3159KB) AllocSpace objects, 2(84KB) LOS objects, 49% free, 6617KB/12MB, paused 142us total 107.565ms
2020-07-26 22:35:56.918 10946-10959/info.metadude.android.congress.schedule.debug I/.schedule.debu: Background young concurrent copying GC freed 60523(3223KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 10MB/12MB, paused 151us total 104.463ms
2020-07-26 22:35:57.250 10946-10946/info.metadude.android.congress.schedule.debug W/View: requestLayout() improperly called by android.widget.LinearLayout{8d60fd2 V.E...... ......ID 0,0-17896,49} during layout: running second layout pass
2020-07-26 22:35:57.251 10946-10946/info.metadude.android.congress.schedule.debug W/View: requestLayout() improperly called by android.widget.TextView{a62e8a3 V.ED..... ......ID 0,0-325,49} during layout: running second layout pass
2020-07-26 22:35:57.251 10946-10946/info.metadude.android.congress.schedule.debug W/View: requestLayout() improperly called by android.widget.TextView{10e7a0 V.ED..... ......ID 325,0-650,49} during layout: running second layout pass
// Many more of the same line
2020-07-26 22:35:57.257 10946-10946/info.metadude.android.congress.schedule.debug W/View: requestLayout() improperly called by android.widget.TextView{544f4cf V.ED..... ......ID 16918,0-17244,49} during layout: running second layout pass
2020-07-26 22:35:57.257 10946-10946/info.metadude.android.congress.schedule.debug W/View: requestLayout() improperly called by android.widget.TextView{80d7e5c V.ED..... ......ID 17244,0-17570,49} during layout: running second layout pass
2020-07-26 22:35:57.257 10946-10946/info.metadude.android.congress.schedule.debug W/View: requestLayout() improperly called by android.widget.TextView{1670565 V.ED..... ......ID 17570,0-17896,49} during layout: running second layout pass
2020-07-26 22:35:57.782 10946-10946/info.metadude.android.congress.schedule.debug I/Choreographer: Skipped 355 frames!  The application may be doing too much work on its main thread.
2020-07-26 22:35:57.905 10946-10988/info.metadude.android.congress.schedule.debug D/MetaDatabaseRepository: query(): Meta(eTag=W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b", numDays=4, subtitle=, title=36th Chaos Communication Congress, version=mkdir; lounges 707; chaos-west 1.0; open-infra 23; wikipaka 0.18; chaoszone 0.14; komona 0.32; sendezentrum 4.5; lightning Holmium; art-play 0.26; cdc 3; wiki 2020-01-18 18:10)
2020-07-26 22:35:57.906 10946-10991/info.metadude.android.congress.schedule.debug D/Fetch: https://raw.githubusercontent.com/voc/36C3_schedule/master/everything.schedule.xml
2020-07-26 22:35:57.907 10946-10991/info.metadude.android.congress.schedule.debug D/Fetch: ETag: W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b"
2020-07-26 22:35:59.364 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: --> GET https://raw.githubusercontent.com/voc/36C3_schedule/master/everything.schedule.xml http/1.1
2020-07-26 22:35:59.364 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: If-None-Match: W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b"
2020-07-26 22:35:59.364 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Host: raw.githubusercontent.com
2020-07-26 22:35:59.364 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Connection: Keep-Alive
2020-07-26 22:35:59.365 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Accept-Encoding: gzip
2020-07-26 22:35:59.365 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: User-Agent: info.metadude.android.congress.schedule.debug, 1.44.0-DEBUG
2020-07-26 22:35:59.365 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: --> END GET
2020-07-26 22:36:00.180 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: <-- 304 Not Modified https://raw.githubusercontent.com/voc/36C3_schedule/master/everything.schedule.xml (814ms)
2020-07-26 22:36:00.181 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Connection: keep-alive
2020-07-26 22:36:00.181 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Date: Sun, 26 Jul 2020 20:35:56 GMT
2020-07-26 22:36:00.181 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Via: 1.1 varnish
2020-07-26 22:36:00.181 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Cache-Control: max-age=300
2020-07-26 22:36:00.182 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: ETag: W/"de271e8ad85983742e5d5a88b57257612e22b22c645e6d92fb1b64b92633b57b"
2020-07-26 22:36:00.182 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: X-Served-By: cache-hhn4063-HHN
2020-07-26 22:36:00.182 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: X-Cache: HIT
2020-07-26 22:36:00.182 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: X-Cache-Hits: 1
2020-07-26 22:36:00.182 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: X-Timer: S1595795757.621645,VS0,VE2
2020-07-26 22:36:00.183 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Vary: Authorization,Accept-Encoding
2020-07-26 22:36:00.183 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Access-Control-Allow-Origin: *
2020-07-26 22:36:00.183 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: X-Fastly-Request-ID: c69a9e005480030045ffde709b51465fc74ec5e6
2020-07-26 22:36:00.183 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Expires: Sun, 26 Jul 2020 20:40:56 GMT
2020-07-26 22:36:00.184 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: Source-Age: 154
2020-07-26 22:36:00.184 10946-10991/info.metadude.android.congress.schedule.debug D/OkHttp: <-- END HTTP
2020-07-26 22:36:00.187 10946-10946/info.metadude.android.congress.schedule.debug D/FetchFahrplan: fetch failed
2020-07-26 22:36:00.199 10946-10946/info.metadude.android.congress.schedule.debug D/AppRepository: Engelsystem shifts URL is empty.

```

---

By the way, after importing the project into IntelliJ, it automatically greeted me with a rendered version of the readme file. Looks pretty neat. Did you somehow set that up or is this a new feature of IntelliJ?

<img width="300" src="https://user-images.githubusercontent.com/5811634/88488296-8dd2e080-cf8c-11ea-8c5d-ca4d740b1a3a.png" />

**Comment by johnjohndoe** [comment] 2020-07-26 21:25
@ByteHamster Thanks for taking your time to look into this.

The underlying problem is not gone but optimized. Basically, @ideadapt added a `RecyclerView` per room which largely sped up the inflation - which is great. See PR #263.
Nevertheless, all rooms of one day are rendered together. The main (tablular) schedule view is not backed by a single recycling mechanism. The view is custom made and does not rely on some Android framework or library magic.

@ideadapt Please correct me if I described it wrong. You dove deeper into the topic than me.

---

The README preview must be IntelliJ's feature. I haven't see it but it will be in Android Studio soon, I believe.

**Comment by johnjohndoe** [comment] 2020-08-01 21:23
# Considered useful
- [Troubleshooting app performance issues with System Trace in Android Studio 4.x](https://www.youtube.com/watch?v=EjmIit_amnE), 31.07.2020
