### ISSUE TITLE
Android 7.0: Certificate could not be added

### ISSUE THREAD

**Issue by rotsq** [EventFahrplan/EventFahrplan#431] opened 2021-12-23 21:43 UTC
# Environment
- App version: [1.53.0-rC3-Edition](https://github.com/EventFahrplan/EventFahrplan/releases/tag/v.1.53.0)
- Android version: 7.0 (Nougat)
- Branch: `master`
- Device: Samsung SM-T815 (Samsung Galaxy Tab S2)

# How to reproduce
1. Open the EventFahrplan app
2. Click _Refresh/Get schedule_ button in the upper right corner
3. The error dialog appears

# Observed behavior
- Error message "Certificate could not be added" (Failed to establish secure connection (SSL handshake terminated: ssl=0x82dab640: Failure in SSL library, usually a protocol error)
- Screenshot added at the bottom of this entry

# Expected behavior
- Downloading/Refreshing the schedule

# Related issues
- https://github.com/EventFahrplan/EventFahrplan/issues/16

![EventFahrplan-SSL-error-20211223-183524](https://user-images.githubusercontent.com/63547723/147293397-68f8faa3-fc1f-43dd-8deb-7f2e4690047f.png)

**Comment by johnjohndoe** [comment] 2021-12-23 23:10
@rotsq Thank you for the error report. I cannot reproduce the behavior yet. Here are some questions which hopefully shed light:

1. Did you install the app fresh or did you update from having the `rC3 Schedule 2020` installed on the device?
2. Can you reproduce the error on another device (with another Android version)?
3. Is the error persisting or did it occur only once? Did you find a workaround?
4. Does the error persist if you clear the cache - or uninstall and reinstall the app? Please backup you favorites before if you made any.

**Comment by rotsq** [comment] 2021-12-24 09:49
@johnjohndoe, answering your questions:
1. `rC3 Schedule 2020` was already installed, I did an update via Google Play.
2. I don't have any other Android device to test on. But given that others did not report this bug and (most likely) the app is already used for upcoming event, I might be a rare case with this situation.
3. The error is persisting, meaning I can recreate this behaviour with every run of the application. I found no workaround. When I click `OK`, nothing happens and when I will click again on `Refresh`, the error reoccurs. If there is the schedule for nowhere already, I don't see it for now, given the app cannot download it.
4. When I cleared data and cache, the situation was the same. Uninstalling and reinstalling the app sadly has exactly the same effect. I tested it with two Internet sources, with or without VPN, no changes in behaviour.

**Comment by johnjohndoe** [comment] 2021-12-24 11:54
Thank you. I suspect it might happen because of the SSL support of the specific Android version. @cketti, @schildbach probably know immediately.

**Comment by schildbach** [comment] 2021-12-24 12:20
Seems like this issue: https://community.letsencrypt.org/t/android-7-0-cant-establish-ssl-connection/152050

**Comment by schildbach** [comment] 2021-12-24 13:10
According to the comments in the issue linked above, the issue can be worked around by the server admins to switch their certificate from ECDSA to RSA, or from EC-384 to EC-256 (bits).

**Comment by johnjohndoe** [comment] 2021-12-24 17:14
@rotsq The issue seems to be specific to Android 7.0 (7.1.1 is not affected) from what I understand from the reseach of @cketti and @schildbach.

A possible workaround is to configure an alternative HTTP URL in the Settings screen of the app. I contacted the rC3 infrastructure team. As soon as an URL is available I will post it here.

**Comment by rotsq** [comment] 2021-12-24 18:32
@johnjohndoe If I'd know the original HTTPS URI I could simply make a workaround for it by passing it through my SSL RSA-key-based infrastructure, but I believe it is `nowhere` to be found in this repository, since it is event-specific. Could I ask you to share it with me? If it is not public, just send me an e-mail.

**Comment by johnjohndoe** [comment] 2021-12-24 18:34
@rotsq No, it is public. It would be great if that works. See here:

https://github.com/EventFahrplan/EventFahrplan/blob/master/app/build.gradle#L123

**Comment by rotsq** [comment] 2021-12-24 18:57
@johnjohndoe It works - if someone will have the same problem and there won't be an official workaround until the event starts (i.e. hosted by CCC) or a solution for the problem, I will share the link in this issue. In the end, it is based on SSL using EC 256 and works well.

**Comment by rotsq** [comment] 2021-12-26 21:53
Here we go with the alternative link for the schedule that works for Android 7.0:

`https://altschedule.world/everything.xml`

The original schedule is fetched every 15 minutes.

**Comment by rotsq** [comment] 2021-12-28 19:02
Isn't there a parsing error for quite some time with recent updates of the schedule, @johnjohndoe? My (over `altschedule`) and my colleague (directly from source) encounter that.

**Comment by johnjohndoe** [comment] 2021-12-28 19:33
@rotsq I saw it once a few minutes ago. @cketti notified me. We try to let c3voc sort it out.

**Comment by johnjohndoe** [comment] 2021-12-28 19:56
@rotsq The parser error is not specific to Android 7.0 nor this issue. @saerdnaer from the c3voc team is working on it.

**Comment by rotsq** [comment] 2021-12-28 19:59
Thank you for this update. I knew that it is unrelated, but I thought that maybe this tread will be OK, sorry if I introduced some confusion.

**Comment by johnjohndoe** [comment] 2021-12-28 20:11
No worries. The latest version should be fine again. Thanks to @cketti and @saerdnaer. I just connected them.

**Comment by johnjohndoe** [comment] 2022-02-02 18:08
Given the workaround I would close this. Not sure if it could easily be patched at the client. Are you okay with this @rotsq?

**Comment by rotsq** [comment] 2022-02-03 08:11
@johnjohndoe, I think we can do so, but I wonder how to have it somewhere noted such that the knowledge on that would be easily findable (but, apparently, there is no wiki). Or, if you believe that searching issues/repository should be enough, it is also fine.

And let me thank also @schildbach and @cketti for investigating the root cause of the problem.

**Closed** 2022-04-08 07:19 UTC
Labels: Bug report, Won't fix, Networking

**Comment by johnjohndoe** [comment] 2022-04-08 07:22
@rotsq In #480 a bit more information is provided - without fixing the root of the issue, though. I don't expect that the error happens too often that it is worth the effort. Also, it would be good to address the issue on the server side.
