### ISSUE TITLE
Allow users to filter rooms 

### ISSUE THREAD

**Issue by LeSnake04** [EventFahrplan/EventFahrplan#528] opened 2022-12-21 21:54 UTC
# Acknowledgments
Please check the following boxes with an `x` if they apply:
* [x] I have read the latest version of the [contribution guide](
  https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md) before creating this pull request.
* [x] I have checked a few other issues labeled `Feature request` to see how they are written.
* [x] The feature I want to propose would be useful for the majority of users, not only for me personally.
* [x] I am aware that _EventFahrplan_ is mostly developed by one person in their unpaid spare time.
* [ ] I can help myself to get this feature implemented or know someone who wants to do it.

# Preliminaries

There are a lot of different local events this year, so there are a lot of rooms all over germany. Most users only care about 1 event. Currently its a mess scrolling to rooms you actually can visit.

# Current state

List all events, no filter option

# Target state

Filter option so users can select rooms they care about

# Hints

It would be great if this could be done and pushed before 27. So we can use the app effectively on the events

**Comment by johnjohndoe** [comment] 2022-12-21 22:04
Please take the time to search through issues before creating a new one. Duplicate of #3.

**Closed by johnjohndoe** 2022-12-21 22:04 UTC
Labels: Duplicate
