### ISSUE TITLE
Hard crash on startup `Too small number of days`

### ISSUE THREAD

**Issue by chohner** [EventFahrplan/EventFahrplan#562] opened 2023-08-17 21:40 UTC
# Environment
- App version: `1.61.0-CCCamp-Edition`
- Android version: 13, GrapheneOS stable build `TQ3A.230805.001.2023080800`
- Branch:
- Device: Google Pixel 7 with GrapheneOS

# How to reproduce
1. Open app

# Observed behavior
- immediate crash on startup
- same after clearing cash

Crash dump
```
type: crash
osVersion: google/panther/panther:13/TQ3A.230805.001/2023080800:user/release-keys
package: info.metadude.android.cccamp.schedule:96
process: info.metadude.android.cccamp.schedule
processUptime: 212 + 232 ms
installer: com.looker.droidify

java.lang.IllegalArgumentException: Too small number of days: 6, date info list contains 8 items
	at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries(NavigationMenuEntriesGenerator.kt:51)
	at nerd.tuxmobil.fahrplan.congress.schedule.NavigationMenuEntriesGenerator.getDayMenuEntries$default(NavigationMenuEntriesGenerator.kt:39)
	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.createFahrplanParameter(FahrplanViewModel.kt:147)
	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel.access$createFahrplanParameter(FahrplanViewModel.kt:34)
	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$fahrplanParameter$2.invokeSuspend(FahrplanViewModel.kt:58)
	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$fahrplanParameter$2.invoke(FahrplanViewModel.kt:0)
	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$fahrplanParameter$2.invoke(FahrplanViewModel.kt:0)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:33)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:0)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:0)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:256)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:590)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2896)
	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:638)
	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:458)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:36)
	at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:304)
	at kotlinx.coroutines.channels.BufferedChannel.send(BufferedChannel.kt:0)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2$1$1.emit(Combine.kt:32)
	at nerd.tuxmobil.fahrplan.congress.schedule.FahrplanViewModel$special$$inlined$filter$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c75d379, Dispatchers.Main.immediate]

```

# Expected behavior
- normal startup

# Related 
- maybe #559

**Comment by chohner** [comment] 2023-08-17 23:27
Fixed by uninstall / reinstall, but lost all favorites :/

**Comment by johnjohndoe** [comment] 2023-08-17 23:47
@chohner sorry to hear that. You could have exported them if you were able to open the app once at least. Thanks for reporting on the issue. From what I know it happens when the number of event days changed. Did you load an old or alternative URL in the app?

**Comment by chohner** [comment] 2023-08-18 07:10
I want to say no but I honestly cannot recall. The hard crash unfortunately makes it impossible to check (or to export favs)

But you are right - Its probable that I did, otherwise more people would've had this issue

**Comment by johnjohndoe** [comment] 2023-09-20 22:22
Duplicate of #529. Closing this one. Let's continue over there.

**Closed by johnjohndoe** 2023-09-20 22:22 UTC
Labels: Bug report, Duplicate
